#!/usr/bin/env bash

RED='\033[0;31m\033[1m'
NC='\033[0m' # No Color

function iferrorcomp ()
{
    if [[ error -eq 1 ]]; then
        printf "$RED\Crit: ERROR had occured during copmile!!\n"
        exit 1
    fi
}
if [[ ! -f $1 || ! $1 && ! -f Makefile ]]; then
    printf "$RED No file/arguments given.\n"
    exit 1
fi

if [[ ${1##*.} == "asm" ]]; then
    printf "\$ nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o\n"
    nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o || error=1
    if [[ error -eq 1 ]]; then
        printf "\n\$ nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o: $RED\error had occured\n"
        exit 1
    fi
    printf "compiled into ${1%.*}.o\n"
    printf "\$ ld ${1%.*}.o -o ${1%.*}\n"
    ld ${1%.*}.o -o ${1%.*} || error=1
    if [[ error -eq 1 ]]; then
        printf "\n\$ ld ${1%.*}.o -o ${1%.*}: $RED\error had occured\n"
        exit 1
    fi
    printf "linked into ${1%.*}\n"
    printf "compiled into executable ${1%.*}\n"
    printf "Running \"${1%.*}\"\n\n"
    ./${1%.*} "${@:2}"
elif [[ ${1##*.} == "c" || ${1##*.} == "cc" ]]; then
    printf "\$ gcc $1 -o ${1%.*}\n"
    gcc $1 -o ${1%.*} || error=1
    if [[ error -eq 1 ]]; then
        printf "\n\$ gcc $1 -o ${1%.*}: $RED\error had occured\n"
        exit 1
    fi
    printf "compiled into ${1%.*}\n"
    printf "Running \"${1%.*}\"\n\n"
    ./${1%.*} "${@:2}"
elif [[ ${1##*.} == "cpp" ]]; then
    printf "\$ g++ $1 -o ${1%.*}\n"
    g++ $1 -o ${1%.*} || error=1
    if [[ error -eq 1 ]]; then
        printf "\n\$ g++ $1 -o ${1%.*}: $RED\error had occured\n"
        exit 1
    fi
    printf "compiled into ${1%.*}\n"
    printf "Running \"${1%.*}\"\n\n"
    ./${1%.*} "${@:2}"
elif [[ ${1##*.} == "go" ]]; then
    printf "\$ go build $1\n"
    go build $1
    if [[ error -eq 1 ]]; then
        printf "\n$RED\Crit: ERROR had occured during build!!\n"
        exit 1
    fi
    printf "compiled\n"
    printf "Running \$ go run $1"
    go run $1 "$@"
elif [[ ${1##*.} == "cs" ]]; then
    printf "\$ csc $1\n"
    csc ${@:2}
    if [[ error -eq 1 ]]; then
        printf "$RED\Crit: ERROR had occured during copmile!!\n"
        exit 1
    fi
    printf "compiled into ${1%.*}.exe\n"
    printf "Running \"${1%.*}\"\n\n"
    mono ${1%.*}.exe "${@:3}"
elif [[ ${1##*.} == "java" ]]; then
    printf "\$ javac $1\n"
    javac $1
    printf "compiled into ${1%.*}.class\n"
    printf "Running \"${1%.*}\"\n\n"
    java ${1%.*} "${@:3}"
elif [[ ${1##*.} == "py" ]]; then
    #printf "\$ pyinstaller -F $1\n"
    #pyinstaller -F $1
    #printf "Running \"./dist/${1%.*}\""
    #./dist/${1%.*} "${@:2}"
    printf "Running ./$@"
#elif [[ ${1##*.} == "rb" ]]; then
    #printf "\$ ruby -wc $1\n"
    #ruby -wc $1
    #printf "compiled into ${1%.*}\n"
    #printf "Running ${1%.*}"
    #ruby $1
elif [[ ${1##*.} == "js" ]]; then
    printf "\$ node $1\n"
    node $1 "${@:3}"
    printf "Running $1"
elif [[ ${1##*.} == "ts" ]]; then
    printf "\$ tsc $1\n"
    tsc $1 "${@:3}"
    printf "compiled into ${1%.*}.js\n"
    printf "Running \$ ts-node $1"
    ts-node $1 "${@:3}"
elif [[ ${1##*.} == "dart" ]]; then
    printf "\$ dart compile exe $1\n"
    dart compile exe $1
    printf "compiled into ${1%.*}\n"
    printf "Running \$ dart $1"
    dart $1 "${@:3}"
elif [[ ${1##*.} == "rs" ]]; then
    printf "\$ rustc $1\n"
    rustc $1
    printf "compiled into ${1%.*}\n"
    printf "Running \$ ./${1%.*}"
    ./${1%.*} "${@:2}"
elif [ -e "Makefile" ]; then
    make
    sudo make install
else
    printf "${RED}ERROR: nothing compiled or runed.\n"
    exit 1
fi
